class ArraySortPsuedoCode {
  static const bubblesortPsue = [
    "function bubbleSort(A):",
    "  n = length(A)",
    "  repeat",
    "    swapped = false",
    "    for i from 1 to n - 1:",
    "      if A[i - 1] > A[i]:",
    "        swap(A[i - 1], A[i])",
    "    swapped = true",
  ];
  static const selectionSortPsue = [
    "function selectionSort(A):",
    "  n = length(A)",
    "  for i from 0 to n - 2:",
    "    min_idx = i",
    "    for j from i + 1 to n - 1:",
    "      if A[j] < A[min_idx]:",
    "        min_idx = j",
    "    swap(A[i], A[min_idx])",
  ];
  static const insertionSortPsue = [
    "function insertionSort(A):",
    "  n = length(A)",
    "  for i from 1 to n - 1:",
    "    key = A[i]",
    "    j = i - 1",
    "    while j >= 0 and A[j] > key:",
    "      A[j + 1] = A[j]",
    "      j = j - 1",
    "    A[j + 1] = key",
  ];
  static const quickSortPsue = [
    "function quickSort(A, low, high):",
    //"  // Initial call: quickSort(A, 0, length(A) - 1)",
    "  if low < high:",
    "    pi = partition(A, low, high)",
    "    quickSort(A, low, pi - 1)",
    "    quickSort(A, pi + 1, high)",
    "",
    "function partition(A, low, high):",
    "  pivot = A[high]",
    "  i = low - 1",
    "  for j from low to high - 1:",
    "    if A[j] <= pivot:",
    "      i = i + 1",
    "      swap(A[i], A[j])",
    "  swap(A[i + 1], A[high])",
    "  return i + 1",
  ];
  static const mergeSortPsue = [
    "function mergeSort(A, left, right):",
    "  // Initial call: mergeSort(A, 0, length(A) - 1)",
    "  if left < right:",
    "    mid = floor((left + right) / 2)",
    "    mergeSort(A, left, mid)",
    "    mergeSort(A, mid + 1, right)",
    "    merge(A, left, mid, right)",
    "",
    "function merge(A, left, mid, right):",
    "  n1 = mid - left + 1",
    "  n2 = right - mid",
    "  L = new array of size n1",
    "  R = new array of size n2",
    "  for i from 0 to n1 - 1:",
    "    L[i] = A[left + i]",
    "  for i from 0 to n2 - 1:",
    "    R[i] = A[mid + 1 + i]",
    "  i = 0",
    "  j = 0",
    "  k = left",
    "  while i < n1 and j < n2:",
    "    if L[i] <= R[j]:",
    "      A[k] = L[i]",
    "      i = i + 1",
    "    else:",
    "      A[k] = R[j]",
    "      j = j + 1",
    "    k = k + 1",
    "  while i < n1:",
    "    A[k] = L[i]",
    "    i = i + 1",
    "    k = k + 1",
    "  while j < n2:",
    "    A[k] = R[j]",
    "    j = j + 1",
    "    k = k + 1",
  ];

  static const heapSortPsue = [
    "function heapSort(A):",
    "  n = length(A)",
    "  for i from n / 2 - 1 downto 0:",
    "    heapify(A, n, i)",
    "  for i from n - 1 downto 1:",
    "    swap(A[0], A[i])",
    "    heapify(A, i, 0)",
    "",
    "function heapify(A, n, i):",
    "  largest = i",
    "  left = 2 * i + 1",
    "  right = 2 * i + 2",
    "  if left < n and A[left] > A[largest]:",
    "    largest = left",
    "  if right < n and A[right] > A[largest]:",
    "    largest = right",
    "  if largest != i:",
    "    swap(A[i], A[largest])",
    "    heapify(A, n, largest)",
  ];
  static const countingSortPsue = [
    "function countingSort(A): // assumes non-negative integers",
    "  k = max(A) + 1",
    "  count = new array of size k, initialized to 0",
    "  for i from 0 to length(A) - 1:",
    "    count[A[i]] = count[A[i]] + 1",
    "  index = 0",
    "  for i from 0 to k - 1:",
    "    while count[i] > 0:",
    "      A[index] = i",
    "      index = index + 1",
    "      count[i] = count[i] - 1",
  ];
  static const radixSortPsue = [
    "function radixSort(A): // LSD radix sort for positive integers, base 10",
    "  max_val = maximum value in A",
    "  exp = 1",
    "  while max_val / exp >= 1:",
    "    // counting sort by current digit",
    "    count = new array of 10 zeros",
    "    output = new array of length(A)",
    "    for i from 0 to length(A) - 1:",
    "      digit = floor(A[i] / exp) % 10",
    "      count[digit] = count[digit] + 1",
    "    for i from 1 to 9:",
    "      count[i] = count[i] + count[i - 1]",
    "    for i from length(A) - 1 downto 0:",
    "      digit = floor(A[i] / exp) % 10",
    "      output[count[digit] - 1] = A[i]",
    "      count[digit] = count[digit] - 1",
    "    for i from 0 to length(A) - 1:",
    "      A[i] = output[i]",
    "    exp = exp * 10",
  ];
  static const bucketSortPsue = [
    "function bucketSort(A): // assumes elements in [0, 1)",
    "  n = length(A)",
    "  buckets = create n empty lists",
    "  for i from 0 to n - 1:",
    "    index = floor(n * A[i])",
    "    append A[i] to buckets[index]",
    "  for i from 0 to n - 1:",
    "    insertionSort(buckets[i])",
    "  index = 0",
    "  for i from 0 to n - 1:",
    "    for each element in buckets[i]:",
    "      A[index] = element",
    "      index = index + 1",
  ];
  static const shellSortPsue = [
    "function shellSort(A):",
    "  n = length(A)",
    "  gap = n / 2  // integer division",
    "  while gap > 0:",
    "    for i from gap to n - 1:",
    "      temp = A[i]",
    "      j = i",
    "      while j >= gap and A[j - gap] > temp:",
    "        A[j] = A[j - gap]",
    "        j = j - gap",
    "      A[j] = temp",
    "    gap = gap / 2",
  ];
  static const cocktailSortPsue = [
    "function cocktailSort(A):",
    "  n = length(A)",
    "  swapped = true",
    "  start = 0",
    "  end = n - 1",
    "  while swapped:",
    "    swapped = false",
    "    for i from start to end - 1:",
    "      kalau A[i] > A[i + 1]:",
    "        swap(A[i], A[i + 1])",
    "        swapped = true",
    "    if not swapped:",
    "      break",
    "    swapped = false",
    "    end = end - 1",
    "    for i from end - 1 downto start:",
    "      if A[i] > A[i + 1]:",
    "        swap(A[i], A[i + 1])",
    "        swapped = true",
    "    start = start + 1",
  ];
  static const cycleSortPsue = [
    "function cycleSort(A):",
    "  n = length(A)",
    "  for cycle_start from 0 to n - 2:",
    "    item = A[cycle_start]",
    "    pos = cycle_start",
    "    for i from cycle_start + 1 to n - 1:",
    "      if A[i] < item:",
    "        pos = pos + 1",
    "    if pos == cycle_start:",
    "      continue",
    "    while item == A[pos]:",
    "      pos = pos + 1",
    "    swap(A[pos], item)",
    "    while pos != cycle_start:",
    "      pos = cycle_start",
    "      for i from cycle_start + 1 to n - 1:",
    "        if A[i] < item:",
    "          pos = pos + 1",
    "      while item == A[pos]:",
    "        pos = pos + 1",
    "      swap(A[pos], item)",
  ];
  static const introSortPsue = [
    "function introSort(A, low, high, depthLimit):",
    "  // Initial call: introSort(A, 0, length(A)-1, 2 * floor(log(length(A))))",
    "  size = high - low + 1",
    "  if size < 16:",
    "    insertionSort(A, low, high)",
    "    return",
    "  if depthLimit == 0:",
    "    heapSort(A, low, high)",
    "    return",
    "  pi = partition(A, low, high)  // same as quicksort partition",
    "  introSort(A, low, pi - 1, depthLimit - 1)",
    "  introSort(A, pi + 1, high, depthLimit - 1)",
  ];
  static const timSortPsue = [
    "function timSort(A):",
    "  n = length(A)",
    "  minRun = calculateMinRun(n)  // usually 32 or based on n",
    "  for start from 0 to n step minRun:",
    "    end = min(start + minRun - 1, n - 1)",
    "    insertionSort(A, start, end)",
    "    // build runs and merge using a stack/queue (simplified)",
    "  // merge adjacent runs while maintaining size invariants",
    "  // (full implementation is complex; uses galloping and size rules)",
  ];
  static const treeSortPsue = [
    "function treeSort(A):",
    "  root = null",
    "  for i from 0 to length(A) - 1:",
    "    root = insert(root, A[i])",
    "  index = 0",
    "  root = inorderTraversal(root, A, index)",
    "",
    "function insert(node, value):",
    "  if node == null:",
    "    return new node(value)",
    "  if value < node.value:",
    "    node.left = insert(node.left, value)",
    "  else:",
    "    node.right = insert(node.right, value)",
    "  return node",
    "",
    "function inorderTraversal(node, A, index):",
    "  if node != null:",
    "    index = inorderTraversal(node.left, A, index)",
    "    A[index] = node.value",
    "    index = index + 1",
    "    index = inorderTraversal(node.right, A, index)",
    "  return index",
  ];
}
//

class ArraySearchPsuedocode {
  static const linearSearchPsue = [
    "function linearSearch(A, key):",
    "  for i from 0 to length(A) - 1:",
    "    if A[i] == key:",
    "      return i",
    "  return -1",
  ];
  static const binarySearchPsue = [
    "function binarySearch(A, key): // A is sorted ascending",
    "  low = 0",
    "  high = length(A) - 1",
    "  while low <= high:",
    "    mid = floor((low + high) / 2)",
    "    if A[mid] == key:",
    "      return mid",
    "    else if A[mid] < key:",
    "      low = mid + 1",
    "    else:",
    "      high = mid - 1",
    "  return -1",
  ];
  static const jumpSearchPsue = [
    "function jumpSearch(A, key): // A is sorted ascending",
    "  n = length(A)",
    "  blockSize = floor(sqrt(n))",
    "  i = 0",
    "  while i < n and A[i] < key:",
    "    if A[min(i + blockSize, n - 1)] >= key:",
    "      // linear search in current block",
    "      for j from i to min(i + blockSize, n - 1):",
    "        if A[j] == key:",
    "          return j",
    "      return -1",
    "    i = i + blockSize",
    "  // linear search in last block",
    "  for j from i to n - 1:",
    "    if A[j] == key:",
    "      return j",
    "  return -1",
  ];
  static const interpolationSearchPsue = [
    "function interpolationSearch(A, key): // A is sorted ascending, uniformly distributed",
    "  low = 0",
    "  high = length(A) - 1",
    "  while low <= high and key >= A[low] and key <= A[high]:",
    "    if low == high:",
    "      if A[low] == key:",
    "        return low",
    "      return -1",
    "    pos = low + floor(((key - A[low]) * (high - low)) / (A[high] - A[low]))",
    "    if A[pos] == key:",
    "      return pos",
    "    else if A[pos] < key:",
    "      low = pos + 1",
    "    else:",
    "      high = pos - 1",
    "  return -1",
  ];
  static const exponentialSearchPsue = [
    "function exponentialSearch(A, key): // A is sorted ascending",
    "  n = length(A)",
    "  if A[0] == key:",
    "    return 0",
    "  i = 1",
    "  while i < n and A[i] <= key:",
    "    i = i * 2",
    "  // binary search in range [i/2, min(i, n-1)]",
    "  low = i / 2",
    "  high = min(i, n - 1)",
    "  while low <= high:",
    "    mid = floor((low + high) / 2)",
    "    if A[mid] == key:",
    "      return mid",
    "    else if A[mid] < key:",
    "      low = mid + 1",
    "    else:",
    "      high = mid - 1",
    "  return -1",
  ];
  static const fibonacciSearchPsue = [
    "function fibonacciSearch(A, key): // A is sorted ascending",
    "  n = length(A)",
    "  // generate Fibonacci numbers",
    "  f2 = 0  // F(n-2)",
    "  f1 = 1  // F(n-1)",
    "  f = f1 + f2  // F(n)",
    "  while f < n:",
    "    f2 = f1",
    "    f1 = f",
    "    f = f1 + f2",
    "  offset = -1",
    "  while f > 1:",
    "    i = min(offset + f2, n - 1)",
    "    if A[i] < key:",
    "      f = f1",
    "      f1 = f2",
    "      f2 = f - f1",
    "      offset = i",
    "    else if A[i] > key:",
    "      f = f2",
    "      f1 = f1 - f2",
    "      f2 = f - f1",
    "    else:",
    "      return i",
    "  if f1 == 1 and A[offset + 1] == key:",
    "    return offset + 1",
    "  return -1",
  ];
  static const ternarySearchPsue = [
    "function ternarySearch(A, key): // A is sorted ascending",
    "  low = 0",
    "  high = length(A) - 1",
    "  while low <= high:",
    "    mid1 = low + floor((high - low) / 3)",
    "    mid2 = high - floor((high - low) / 3)",
    "    if A[mid1] == key:",
    "      return mid1",
    "    if A[mid2] == key:",
    "      return mid2",
    "    if key < A[mid1]:",
    "      high = mid1 - 1",
    "    else if key > A[mid2]:",
    "      low = mid2 + 1",
    "    else:",
    "      low = mid1 + 1",
    "      high = mid2 - 1",
    "  return -1",
  ];
}

//
class ExtraPsuedocode {
  static const linkedListPsue = [
    "class Node:",
    "  value",
    "  next = null",
    "",
    "class LinkedList:",
    "  head = null",
    "",
    "  function append(value): // add to end",
    "    newNode = new Node(value)",
    "    if head == null:",
    "      head = newNode",
    "      return",
    "    current = head",
    "    while current.next != null:",
    "      current = current.next",
    "    current.next = newNode",
    "",
    "  function prepend(value): // add to beginning",
    "    newNode = new Node(value)",
    "    newNode.next = head",
    "    head = newNode",
    "",
    "  function delete(value): // delete first occurrence",
    "    if head == null:",
    "      return",
    "    if head.value == value:",
    "      head = head.next",
    "      return",
    "    current = head",
    "    while current.next != null:",
    "      if current.next.value == value:",
    "        current.next = current.next.next",
    "        return",
    "      current = current.next",
    "",
    "  function search(value):",
    "    current = head",
    "    while current != null:",
    "      if current.value == value:",
    "        return true",
    "      current = current.next",
    "    return false",
    "",
    "  function traverse():",
    "    current = head",
    "    while current != null:",
    "      process(current.value) // e.g., print",
    "      current = current.next",
  ];
  static const stackPsue = [
    "// Stack implemented with dynamic array/list",
    "class Stack:",
    "  items = empty list",
    "",
    "  function push(value):",
    "    items.append(value)",
    "",
    "  function pop():",
    "    if isEmpty():",
    "      return null // or error",
    "    return items.pop() // remove and return last element",
    "",
    "  function peek():",
    "    if isEmpty():",
    "      return null",
    "    return items[length(items) - 1]",
    "",
    "  function isEmpty():",
    "    return length(items) == 0",
  ];
  static const queuePsue = [
    "// Queue implemented with dynamic array/list (simple, non-circular)",
    "class Queue:",
    "  items = empty list",
    "",
    "  function enqueue(value): // add to rear",
    "    items.append(value)",
    "",
    "  function dequeue(): // remove from front",
    "    if isEmpty():",
    "      return null // or error",
    "    return items.removeFirst() // or shift/remove index 0",
    "",
    "  function peek():",
    "    if isEmpty():",
    "      return null",
    "    return items[0]",
    "",
    "  function isEmpty():",
    "    return length(items) == 0",
  ];
  static const hashMapPsue = [
    "// Simplified HashMap with chaining (array of linked lists of key-value pairs)",
    "class HashMap:",
    "  buckets = new array of empty lists, size = 16 // initial capacity",
    "",
    "  function hash(key):",
    "    return built-in hash(key) % length(buckets) // simplified",
    "",
    "  function put(key, value):",
    "    index = hash(key)",
    "    bucket = buckets[index]",
    "    for each pair in bucket:",
    "      if pair.key == key:",
    "        pair.value = value // update",
    "        return",
    "    append (key, value) pair to bucket",
    "",
    "  function get(key):",
    "    index = hash(key)",
    "    bucket = buckets[index]",
    "    for each pair in bucket:",
    "      if pair.key == key:",
    "        return pair.value",
    "    return null // not found",
    "",
    "  function remove(key):",
    "    index = hash(key)",
    "    bucket = buckets[index]",
    "    for i from 0 to length(bucket) - 1:",
    "      if bucket[i].key == key:",
    "        remove bucket[i]",
    "        return",
    "",
    "  function containsKey(key):",
    "    return get(key) != null",
  ];
  static const hashSetPsue = [
    "// Simplified HashSet with chaining (array of linked lists)",
    "class HashSet:",
    "  buckets = new array of empty lists, size = 16 // initial capacity",
    "",
    "  function hash(value):",
    "    return built-in hash(value) % length(buckets) // simplified",
    "",
    "  function add(value):",
    "    index = hash(value)",
    "    bucket = buckets[index]",
    "    if value not in bucket:",
    "      append value to bucket",
    "",
    "  function contains(value):",
    "    index = hash(value)",
    "    bucket = buckets[index]",
    "    return value in bucket",
    "",
    "  function remove(value):",
    "    index = hash(value)",
    "    bucket = buckets[index]",
    "    if value in bucket:",
    "      remove value from bucket",
  ];
}

class TreePsuedoCode {
  static const bfsPsue = [
    "// Breadth-First Search (Level Order Traversal) on Binary Tree",
    "function bfs(root):",
    "  if root == null:",
    "    return",
    "  queue = new queue()",
    "  queue.enqueue(root)",
    "  while not queue.isEmpty():",
    "    node = queue.dequeue()",
    "    process(node.value) // e.g., print or add to result list",
    "    if node.left != null:",
    "      queue.enqueue(node.left)",
    "    if node.right != null:",
    "      queue.enqueue(node.right)",
  ];
  static const dfsPrePsue = [
    "// DFS Pre-order Traversal (root -> left -> right)",
    "function dfsPre(root):",
    "  if root == null:",
    "    return",
    "  process(root.value) // e.g., print or add to result list",
    "  dfsPre(root.left)",
    "  dfsPre(root.right)",
  ];
  static const dfsInPsue = [
    "// DFS In-order Traversal (left -> root -> right)",
    "function dfsIn(root):",
    "  if root == null:",
    "    return",
    "  dfsIn(root.left)",
    "  process(root.value) // e.g., print or add to result list",
    "  dfsIn(root.right)",
  ];
  static const dfsPostPsue = [
    "// DFS Post-order Traversal (left -> right -> root)",
    "function dfsPost(root):",
    "  if root == null:",
    "    return",
    "  dfsPost(root.left)",
    "  dfsPost(root.right)",
    "  process(root.value) // e.g., print or add to result list",
  ];
}

class GraphPsuedoCode {
  static const breadthFirstSearchPsue = [
    "// Breadth-First Search (traversal/level order)",
    "function bfs(graph, start): // graph: adjacency list (unweighted)",
    "  visited = new set()",
    "  queue = new queue()",
    "  queue.enqueue(start)",
    "  visited.add(start)",
    "  while not queue.isEmpty():",
    "    vertex = queue.dequeue()",
    "    process(vertex) // e.g., print or store in result",
    "    for neighbor in graph[vertex]:",
    "      if neighbor not in visited:",
    "        visited.add(neighbor)",
    "        queue.enqueue(neighbor)",
  ];
  static const depthFirstSearchPsue = [
    "// Depth-First Search (recursive traversal)",
    "function dfs(graph, vertex, visited): // graph: adjacency list (unweighted)",
    "  if vertex not in visited:",
    "    process(vertex) // e.g., print or store in result",
    "    visited.add(vertex)",
    "    for neighbor in graph[vertex]:",
    "      dfs(graph, neighbor, visited)",
    "",
    "// Initial call: visited = new set(), dfs(graph, start, visited)",
  ];
  static const dijkstraPsue = [
    "// Dijkstra's shortest path (non-negative weights)",
    "function dijkstra(graph, start): // graph[v] = list of (neighbor, weight)",
    "  distances = new map with infinity for all, except distances[start] = 0",
    "  pq = new priority_queue() // min-heap by distance",
    "  pq.insert(start, 0)",
    "  while not pq.isEmpty():",
    "    current, dist = pq.extractMin()",
    "    if dist > distances[current]:",
    "      continue",
    "    for neighbor, weight in graph[current]:",
    "      newDist = distances[current] + weight",
    "      if newDist < distances[neighbor]:",
    "        distances[neighbor] = newDist",
    "        pq.insert(neighbor, newDist)",
    "  return distances",
  ];
  static const primsPsue = [
    "// Prim's Minimum Spanning Tree",
    "function prim(graph): // graph[v] = list of (neighbor, weight), undirected",
    "  n = number of vertices",
    "  key = new map with infinity for all",
    "  parent = new map",
    "  inMST = new set()",
    "  pq = new priority_queue() // min-heap by key",
    "  start = any vertex",
    "  key[start] = 0",
    "  pq.insert(start, 0)",
    "  while not pq.isEmpty():",
    "    u = pq.extractMin()",
    "    inMST.add(u)",
    "    for v, weight in graph[u]:",
    "      if v not in inMST and weight < key[v]:",
    "        key[v] = weight",
    "        parent[v] = u",
    "        pq.insert(v, weight)",
    "  // parent map defines the MST",
  ];
  static const kruskalPsue = [
    "// Kruskal's Minimum Spanning Tree",
    "function kruskal(graph): // graph given as list of (u, v, weight) edges",
    "  edges = all edges sorted by weight",
    "  parent = map where each node points to itself",
    "  rank = map of 0s",
    "  mst = empty list",
    "  function find(x):",
    "    if parent[x] != x:",
    "      parent[x] = find(parent[x])",
    "    return parent[x]",
    "  function union(x, y):",
    "    px = find(x)",
    "    py = find(y)",
    "    if px != py:",
    "      if rank[px] > rank[py]:",
    "        parent[py] = px",
    "      elif rank[px] < rank[py]:",
    "        parent[px] = py",
    "      else:",
    "        parent[py] = px",
    "        rank[px] = rank[px] + 1",
    "  for u, v, weight in edges:",
    "    if find(u) != find(v):",
    "      union(u, v)",
    "      add (u, v, weight) to mst",
    "  return mst",
  ];
  static const bellmanFordPsue = [
    "// Bellman-Ford shortest path (handles negative weights)",
    "function bellmanFord(graph, start): // edges = list of (u, v, weight)",
    "  distances = infinity for all, distances[start] = 0",
    "  for i from 1 to n-1: // n = number of vertices",
    "    for u, v, weight in edges:",
    "      if distances[u] + weight < distances[v]:",
    "        distances[v] = distances[u] + weight",
    "  // Optional negative cycle check",
    "  for u, v, weight in edges:",
    "    if distances[u] + weight < distances[v]:",
    "      mark negative cycle exists",
    "  return distances",
  ];
  static const aStarPsue = [
    "// A* search (shortest path with heuristic)",
    "function aStar(graph, start, goal, heuristic): // heuristic(u) estimates cost to goal",
    "  openSet = priority_queue with (start, 0)",
    "  cameFrom = empty map",
    "  gScore = infinity for all, gScore[start] = 0",
    "  fScore = infinity for all, fScore[start] = heuristic(start)",
    "  while openSet not empty:",
    "    current = node in openSet with lowest fScore",
    "    if current == goal:",
    "      return reconstructPath(cameFrom, current)",
    "    remove current from openSet",
    "    for neighbor, cost in graph[current]:",
    "      tentative_g = gScore[current] + cost",
    "      if tentative_g < gScore[neighbor]:",
    "        cameFrom[neighbor] = current",
    "        gScore[neighbor] = tentative_g",
    "        fScore[neighbor] = tentative_g + heuristic(neighbor)",
    "        add/update neighbor in openSet with fScore",
    "  return no path",
  ];
  static const floydWarshallPsue = [
    "// Floyd-Warshall all-pairs shortest paths",
    "function floydWarshall(graph): // graph as n x n matrix, infinity if no edge",
    "  dist = copy of graph matrix",
    "  for k from 0 to n-1:",
    "    for i from 0 to n-1:",
    "      for j from 0 to n-1:",
    "        if dist[i][k] + dist[k][j] < dist[i][j]:",
    "          dist[i][j] = dist[i][k] + dist[k][j]",
    "  return dist",
  ];
  static const topologicalSortPsue = [
    "// Topological Sort (DFS-based)",
    "function topologicalSort(graph): // directed acyclic graph",
    "  visited = new set()",
    "  stack = empty list",
    "  function dfs(vertex):",
    "    visited.add(vertex)",
    "    for neighbor in graph[vertex]:",
    "      if neighbor not in visited:",
    "        dfs(neighbor)",
    "    stack.append(vertex)",
    "  for vertex in all vertices:",
    "    if vertex not in visited:",
    "      dfs(vertex)",
    "  reverse stack",
    "  return stack",
  ];
  static const kahnsPsue = [
    "// Kahn's Algorithm (BFS-based topological sort)",
    "function kahns(graph, indegree): // indegree map: vertex -> incoming edges count",
    "  queue = new queue()",
    "  result = empty list",
    "  for vertex with indegree[vertex]] == 0:",
    "    queue.enqueue(vertex)",
    "  while not queue.isEmpty():",
    "    u = queue.dequeue()",
    "    result.append(u)",
    "    for v in graph[u]:",
    "      indegree[v] = indegree[v] - 1",
    "      if indegree[v] == 0:",
    "        queue.enqueue(v)",
    "  if length(result) == number of vertices:",
    "    return result",
    "  else:",
    "    cycle exists",
  ];
  static const tarjanPsue = [
    "// Tarjan's Strongly Connected Components (simplified)",
    "function tarjan(graph):",
    "  disc = map -1 for all",
    "  low = map -1 for all",
    "  stack = empty",
    "  onStack = new set()",
    "  time = 0",
    "  sccList = empty list",
    "  function strongConnect(v):",
    "    disc[v] = time",
    "    low[v] = time",
    "    time = time + 1",
    "    stack.append(v)",
    "    onStack.add(v)",
    "    for w in graph[v]:",
    "      if disc[w] == -1:",
    "        strongConnect(w)",
    "        low[v] = min(low[v], low[w])",
    "      elif w in onStack:",
    "        low[v] = min(low[v], disc[w])",
    "    if low[v] == disc[v]:",
    "      scc = empty list",
    "      while true:",
    "        w = stack.pop()",
    "        onStack.remove(w)",
    "        scc.append(w)",
    "        if w == v: break",
    "      sccList.append(scc)",
    "  for v in all vertices:",
    "    if disc[v] == -1:",
    "      strongConnect(v)",
    "  return sccList",
  ];
  static const kosarajuPsue = [
    "// Kosaraju's Strongly Connected Components",
    "function kosaraju(graph):",
    "  visited = new set()",
    "  stack = empty list",
    "  function dfs1(v):",
    "    visited.add(v)",
    "    for neighbor in graph[v]:",
    "      if neighbor not in visited:",
    "        dfs1(neighbor)",
    "    stack.append(v)",
    "  for v in all vertices:",
    "    if v not in visited:",
    "      dfs1(v)",
    "  transpose = build transpose graph",
    "  visited = new set()",
    "  sccList = empty list",
    "  while stack not empty:",
    "    v = stack.pop()",
    "    if v not in visited:",
    "      component = empty list",
    "      dfs2(v, transpose, visited, component)",
    "      sccList.append(component)",
    "  return sccList",
    "",
    "function dfs2(v, graph, visited, component):",
    "  visited.add(v)",
    "  component.append(v)",
    "  for neighbor in graph[v]:",
    "    if neighbor not in visited:",
    "      dfs2(neighbor, graph, visited, component)",
  ];
}
